grails-app/domain/gocharges/Payer.groovy
src/main/groovy/gocharges/domain/base/BaseEntity.groovy

Pequenas alterações na classe Payer também foram realizadas

BaseEntity criada

---

README.md

- Alteração do arquivo README, completando com os 2 colaboradores do projeto e adicionando a documentação base.
- Não possui.

Alterando README (Autores e Documentação)

---

grails-app/services/gocharges/CustomerService.groovy

- Implementação do método de SoftDelete do Domínio de Customer utilizando do atributo deleted
- Não possui.

Implementação do softDelete do domínio de Customer

---

grails-app/controllers/gocharges/PayerController.groovy
grails-app/services/gocharges/PayerService.groovy

- Implementação do método de SoftDelete do Domínio de Payer utilizando do atributo deleted
- Não possui.

Implementação do método de soft delete do Payer

---

grails-app/controllers/gocharges/PaymentController.groovy
grails-app/domain/gocharges/Payment.groovy
grails-app/services/gocharges/PaymentService.groovy
grails-app/views/payment/index.gsp

Classe Payment herdando de BaseEntity e soft delete implementado
- https://github.com/pedrooalves/goCharges/pull/9

Payment soft delete

---

grails-app/controllers/gocharges/PaymentController.groovy
grails-app/services/gocharges/PaymentService.groovy
src/main/groovy/gocharges/payment/PaymentRepository.groovy

- Payment repository implementado
- https://github.com/pedrooalves/goCharges/pull/14

Payment repository

---

grails-app/controllers/gocharges/CustomerController.groovy
grails-app/services/gocharges/CustomerService.groovy
src/main/groovy/gocharges/customer/CustomerRepository.groovy

- CustomerRepository criado
- Métodos de consulta delegados ao repository
- https://github.com/pedrooalves/goCharges/pull/11

Customer repository

---

grails-app/controllers/gocharges/PayerController.groovy
grails-app/services/gocharges/PayerService.groovy
src/main/groovy/gocharges/payer/PayerRepository.groovy

- Implementando um Repositório para a Payer e realizando a troca dos métodos de buscas por queries do Repository.
- Após esse PR ser revisado e corrigido, irei efetuar as alterações do método de listagem da Payer que foi comentado durante esse PR: https://github.com/pedrooalves/goCharges/pull/12#discussion_r1204780846
- Não possui.

Repository payer

---

README.md

- Adicionando link do Quadro de Tasks na README.md
- Não possui

Trello readme

---

.gitignore

- Ignorando classes de teste.
- Não possui

Ignorando classes de teste

---

grails-app/controllers/gocharges/UserController.groovy
grails-app/i18n/messages_pt_BR.properties
grails-app/services/gocharges/UserService.groovy
grails-app/utils/shared/Utils.groovy
grails-app/views/layouts/main.gsp
grails-app/views/user/signup.gsp
src/main/groovy/gocharges/auth/role/RoleRepository.groovy
src/main/groovy/gocharges/auth/role/enums/RoleAuthority.groovy
src/main/groovy/gocharges/auth/user/UserRepository.groovy
src/main/groovy/gocharges/auth/user/adapter/UserAdapter.groovy
src/main/groovy/gocharges/auth/userrole/UserRoleRepository.groovy

- Cadastro de User criado
- Repositories de User, Role e UserRole foram criados
- https://github.com/pedrooalves/goCharges/pull/21

User sign up

---

grails-app/utils/shared/FlashMessageType.groovy

- Adicionando FlashMessageType para alterar os Maps validation
- Não possui

FlashMessageType criada

---

grails-app/utils/shared/CustomDateUtils.groovy

- Classe CustomDateUtils criada
- Não possui

CustomDateUtils

---

grails-app/i18n/messages_pt_BR.properties
grails-app/taglib/gocharges/FormatTagLib.groovy

- Adição da TagLib de formatações (Cpf, Cnpj, Datas e Métodos de Pagamento)

TagLib de Formatações

---

grails-app/controllers/gocharges/PayerController.groovy
grails-app/views/payer/create.gsp
grails-app/views/payer/index.gsp

- Movendo o formulário de criação de pagador para uma tela separada.
- Descontinuação do showForm.
- https://github.com/pedrooalves/goCharges/pull/53
- https://trello.com/c/1Uvm9E0E

Formulário Payer

---

grails-app/taglib/gocharges/FormatTagLib.groovy
grails-app/views/payment/edit.gsp
grails-app/views/payment/index.gsp

- Trocando namespace da FormatTagLib para camelCase 

Namespace FormatTagLib

---

src/main/groovy/gocharges/payment/enums/PaymentStatus.groovy

- Criação do PaymentStatus Confirmed para cobranças confirmadas em cartão de crédito

Criação do PaymentStatus Confirmed

---

grails-app/services/gocharges/CustomerService.groovy
grails-app/services/gocharges/PayerService.groovy
grails-app/utils/shared/enums/State.groovy
grails-app/views/customer/create.gsp
grails-app/views/payer/create.gsp
grails-app/views/payer/edit.gsp
src/main/groovy/gocharges/domain/base/BasePerson.groovy

- Enum de estados criado
- Input de estado alterado para select
- https://github.com/pedrooalves/goCharges/pull/37

Enum de Estados

---

grails-app/controllers/gocharges/CustomerController.groovy
grails-app/controllers/gocharges/PayerController.groovy
grails-app/controllers/gocharges/PaymentController.groovy
grails-app/controllers/gocharges/PaymentReceiptController.groovy
grails-app/controllers/gocharges/UserController.groovy
src/main/groovy/gocharges/controller/base/BaseController.groovy

- Criando tratador de exceções no BaseController
- Deixar código mais enxuto, extraindo tratamento em cada método dos controller para um método específico.
- https://trello.com/c/n04aTZk5

Criação tratador de exceções

---

grails-app/controllers/gocharges/UserController.groovy

- Removendo duplicidade de método do springSecurityService na userController para remover erro ao acessar myAccount

Removendo duplicidade de springSecurityService

---

grails-app/views/user/login.gsp
grails-app/views/user/signup.gsp

- Padronização das telas de Cadastro e Login
- https://trello.com/c/Ln5GuadY

Padronização telas de Cadastro e Login

---

grails-app/controllers/gocharges/CustomerController.groovy
grails-app/controllers/gocharges/UserController.groovy
grails-app/views/notFound.gsp

- Retornando mensagem de erro de credenciais em tela.
- Criação tela de NotFound que retorna para a tela que foi chamada.

Retornando erro de credenciais & Tela de NotFound
